name: "\U0001F41E Bug report"
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false
  - type: input
    id: blocky-version
    attributes:
      label: Blocky version
      description: The version of the Blocky DNS proxy you are running.
      placeholder: e.g. v0.28.2
    validations:
      required: true
  - type: input
    id: blockyui-version
    attributes:
      label: BlockyUI version
      description: The version of BlockyUI you are using.
      placeholder: e.g. v1.5.0
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where are you experiencing the issue?
      multiple: true
      options:
        - Desktop
        - Mobile
        - Other
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. Windows 11, macOS 14, Ubuntu 24.04, iOS 18
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome 130, Safari 18, Firefox 132
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
